### PR TITLE
adds s3 bucket to test aws provider (expected to fail)

### PR DESCRIPTION
**Pull request by prestonwrthompson**

### CODE REVIEW

**Comment by atlantis-bot-pt** [comment]
Ran Plan for dir: `aws/us-east-1` workspace: `default`

**Plan Error**
```
running "terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/prestonwrthompson/atlantis-test/3/default/aws/us-east-1/default.tfplan\" -var atlantis_user=\"prestonwrthompson\" -var atlantis_repo=\"prestonwrthompson/atlantis-test\" -var atlantis_repo_name=\"atlantis-test\" -var atlantis_repo_owner=\"prestonwrthompson\" -var atlantis_pull_num=3" in "/home/atlantis/.atlantis/repos/prestonwrthompson/atlantis-test/3/default/aws/us-east-1": exit status 1

Error: provider.aws: "region": required field is not set



```

**Comment by atlantis-bot-pt** [comment]
Ran Plan for dir: `aws/us-east-1` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/prestonwrthompson/atlantis-test/3/default/aws/us-east-1/default.tfplan\" -var atlantis_user=\"prestonwrthompson\" -var atlantis_repo=\"prestonwrthompson/atlantis-test\" -var atlantis_repo_name=\"atlantis-test\" -var atlantis_repo_owner=\"prestonwrthompson\" -var atlantis_pull_num=3" in "/home/atlantis/.atlantis/repos/prestonwrthompson/atlantis-test/3/default/aws/us-east-1": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.aws: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider



```
</details>

**Comment by prestonwrthompson** [comment]
atlantis plan

**Comment by atlantis-bot-pt** [comment]
Ran Plan for dir: `aws/us-east-1` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ aws_s3_bucket.bucket
      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "test-atlantis-2019-03-13"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      tags.%:                      "1"
      tags.Name:                   "AtlantisTestBucket"
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d aws/us-east-1`
* :put_litter_in_its_place: To **delete** this plan click [here](http://57a4056bc1c5:4141/lock?id=prestonwrthompson%252Fatlantis-test%252Faws%252Fus-east-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d aws/us-east-1`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by prestonwrthompson** [comment]
atlantis apply

**Comment by atlantis-bot-pt** [comment]
Ran Apply for dir: `aws/us-east-1` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_s3_bucket.bucket: Creating...
  acceleration_status:         "" => "<computed>"
  acl:                         "" => "private"
  arn:                         "" => "<computed>"
  bucket:                      "" => "test-atlantis-2019-03-13"
  bucket_domain_name:          "" => "<computed>"
  bucket_regional_domain_name: "" => "<computed>"
  force_destroy:               "" => "false"
  hosted_zone_id:              "" => "<computed>"
  region:                      "" => "<computed>"
  request_payer:               "" => "<computed>"
  tags.%:                      "" => "1"
  tags.Name:                   "" => "AtlantisTestBucket"
  versioning.#:                "" => "<computed>"
  website_domain:              "" => "<computed>"
  website_endpoint:            "" => "<computed>"
aws_s3_bucket.bucket: Creation complete after 1s (ID: test-atlantis-2019-03-13)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```
</details>

**Comment by atlantis-bot-pt** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `aws/us-east-1` workspace: `default`

**Pull request merged**
