### PR TITLE
adds a provider and null resource to test atlantis

### PR DESCRIPTION
**Pull request by prestonwrthompson**

### CODE REVIEW

**Comment by atlantis-bot-pt** [comment]
Ran Plan for dir: `aws/us-east-1` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.null
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d aws/us-east-1`
* :put_litter_in_its_place: To **delete** this plan click [here](http://2c1dbf65b40f:4141/lock?id=prestonwrthompson%252Fatlantis-test%252Faws%252Fus-east-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d aws/us-east-1`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by atlantis-bot-pt** [comment]
**Warning**: The plan for dir: `aws/us-east-1` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by prestonwrthompson** [comment]
atlantis plan

**Comment by atlantis-bot-pt** [comment]
Ran Plan for dir: `aws/us-east-1` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ null_resource.null
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d aws/us-east-1`
* :put_litter_in_its_place: To **delete** this plan click [here](http://2c1dbf65b40f:4141/lock?id=prestonwrthompson%252Fatlantis-test%252Faws%252Fus-east-1%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d aws/us-east-1`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by prestonwrthompson** [comment]
atlantis apply

**Comment by atlantis-bot-pt** [comment]
Ran Apply for dir: `aws/us-east-1` workspace: `default`

```diff
null_resource.null: Creating...
null_resource.null: Creation complete after 0s (ID: 7934266459457694372)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by atlantis-bot-pt** [comment]
**Warning**: The plan for dir: `aws/us-east-1` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Pull request merged**
